# Generated by Django 4.2.1 on 2023-05-31 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('branchID', models.IntegerField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=50)),
                ('barangay', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('zipCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='deliveryPersonnel',
            fields=[
                ('dpId', models.IntegerField(primary_key=True, serialize=False)),
                ('lName', models.CharField(max_length=20)),
                ('fName', models.CharField(max_length=20)),
                ('mInit', models.CharField(max_length=1)),
                ('branchID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ewallet',
            fields=[
                ('walletID', models.IntegerField(primary_key=True, serialize=False)),
                ('walletPass', models.CharField(max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ewallet_transaction',
            fields=[
                ('transactionID', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transactionType', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('walletID', models.IntegerField()),
                ('orderID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentType', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('userID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('productID', models.IntegerField()),
                ('orderID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='points',
            fields=[
                ('pointID', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=12)),
                ('totalPoints', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='points_transaction',
            fields=[
                ('transactionID', models.IntegerField(primary_key=True, serialize=False)),
                ('pointsReduced', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('pointID', models.IntegerField()),
                ('rewardID', models.IntegerField()),
                ('walletID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('productID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('productCategory', models.CharField(max_length=20)),
                ('productName', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=50)),
                ('productImage', models.URLField()),
                ('isFeatured', models.BooleanField()),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='recovery_codes',
            fields=[
                ('codeID', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('status', models.BooleanField()),
                ('walletID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='reward',
            fields=[
                ('rewardID', models.IntegerField(primary_key=True, serialize=False)),
                ('requiredPoints', models.IntegerField()),
                ('rewardExpDate', models.DateField()),
                ('productID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('phoneNum', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('lName', models.CharField(max_length=20)),
                ('fName', models.CharField(max_length=20)),
                ('mInit', models.CharField(max_length=1)),
                ('street', models.CharField(max_length=50)),
                ('barangay', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userCreatesEwallet',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('walletID', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='userHasInfo',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('fullname', models.IntegerField()),
                ('fullAddress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userReceivesPoints',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('pointID', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='workerHasBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('branchID', models.IntegerField()),
                ('fullAddress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='workerHasDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('dpId', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('fullname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='workerPortal',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('accountType', models.CharField(max_length=50)),
                ('phoneNum', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField()),
                ('prodfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penny_one.products')),
            ],
        ),
        migrations.CreateModel(
            name='drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=50)),
                ('isSpecialty', models.BooleanField()),
                ('cupSize', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField()),
                ('prodfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penny_one.products')),
            ],
        ),
    ]
