# Generated by Django 4.2.1 on 2023-05-28 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penny_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ewallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletID', models.IntegerField(max_length=11)),
                ('walletPass', models.CharField(max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ewallet_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.IntegerField(max_length=11)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transactionType', models.IntegerField(max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.IntegerField(max_length=11)),
                ('status', models.IntegerField(max_length=1)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentType', models.IntegerField(max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.IntegerField(max_length=11)),
                ('quantity', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointID', models.IntegerField(max_length=11)),
                ('barcode', models.CharField(max_length=12)),
                ('totalPoints', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='points_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.IntegerField(max_length=11)),
                ('pointsReduced', models.IntegerField(max_length=11)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.IntegerField(max_length=11)),
                ('productCategory', models.CharField(max_length=20)),
                ('productName', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=50)),
                ('productImage', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='recovery_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeID', models.IntegerField(max_length=11)),
                ('code', models.CharField(max_length=6)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewardID', models.IntegerField(max_length=11)),
                ('requiredPoints', models.IntegerField(max_length=3)),
                ('rewardExpDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('phoneNum', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField(max_length=11)),
                ('lName', models.CharField(max_length=20)),
                ('fName', models.CharField(max_length=20)),
                ('mInit', models.CharField(max_length=1)),
                ('street', models.CharField(max_length=50)),
                ('barangay', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.CreateModel(
            name='drink',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='penny_one.products')),
                ('flavor', models.CharField(max_length=50)),
                ('cupSize', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField()),
                ('status', models.IntegerField(max_length=1)),
            ],
            bases=('penny_one.products',),
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='penny_one.products')),
                ('unit', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField()),
                ('status', models.IntegerField(max_length=1)),
            ],
            bases=('penny_one.products',),
        ),
    ]
